Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace sybatnetwork.Controllers
{
    public class BlogsController : Controller
    {
        private const string webTitle = "Blog";
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["Title"] = webTitle;
            return View();
        }
        public IActionResult Whitepaper()
        {
            ViewData["Title"] = "Blogs | Sybatcoin Whitepaper";
            return View();
        }
        public IActionResult Stateless()
        {
            ViewData["Title"] = "Blogs | Stateless Technology";
            return View();
        }
    }
}

Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace sybatnetwork.Controllers
{
    public class NewController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["Title"] = "What's new";
            return View();
        }
        public IActionResult Lavender()
        {
            ViewData["Title"] = "Syabtcoin Lavender";
            return View();
        }
        public IActionResult Core()
        {
            ViewData["Title"] = "Sybatcoin Core";
            return View();
        }
        public IActionResult QubitnaryNumbers()
        {
            ViewData["Title"] = "Qubitnary Numbers";
            return View();
        }
        public IActionResult QoKa()
        {
            ViewData["Title"] = "QoKa";
            return View();
        }
    }
}

Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace sybatnetwork.Controllers
{
    public class ResourcesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["Title"] = "Resoutces";
            return View();
        }
        public IActionResult Exchanges()
        {
            ViewData["Title"] = "Sybatcoin Listing & Exchanges";
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sybat Network</title>
    <meta name="description" content="Sybat Network: An Ecosystem of Quantum Blockchain Technology into Computer Software." />
    <meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/docs.css">
    <link rel="stylesheet" href="https://cdn.tailwindcss.com" />

    <meta property="og:locale" content="en_US" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Sybat Network: An Ecosystem of Blockchain Technology into Computer Software." />
    <meta property="og:description" content="Sybat Network: An Ecosystem of Blockchain Technology into Computer Software." />
    <meta property="og:url" content="https://sybat.network/" />
    <meta property="og:site_name" content="Sybat Network" />
    <meta property="og:image" content="https://sybat.network/img/facebook.pngg" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:description" content="Sybat Network: An Ecosystem of Blockchain Technology into Computer Software." />
    <meta name="twitter:title" content="Sybat Network: An Ecosystem of Blockchain Technology into Computer Software."  />
    <meta name="twitter:image" content="https://sybat.network/img/tweet.png" />
    <meta name="msvalidate.01" content="97954F3D68BFAF156D19B178C2B327F7" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" alt="logo" /> Sybat Network</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse float-right">
                    <a class="text-center nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Contact" style="font-size: 14px; color: #ffffff; background-color: #F4F3EE; border-radius: 3px;">Contact Sales</a>
                    <ul class="navbar-nav flex-grow-1 ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 14px;">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solutions" asp-action="Index" style="font-size: 14px;">Solutions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dev" asp-action="Index" style="font-size: 14px;">Developer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ecosystem" asp-action="Index" style="font-size: 14px;">Ecosystem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Community" asp-action="Index" style="font-size: 14px;">Community</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blogs" asp-action="Index" style="font-size: 14px;">Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wallet" asp-action="Index" style="font-size: 14px;">Wallet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Support" asp-action="Index" style="font-size: 14px;">Support</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid p-2">
        <main role="main" class="pb-0">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container-fluid p-4" style="background-color: #373737;">
            <div class="row">
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <ul>
                        <h5 style="color: #ffffff;">What's New</h5>
                        <li><a asp-area="" asp-controller="New" asp-action="Index">Sybatcoin</a></li>
                        <li><a asp-area="" asp-controller="New" asp-action="Core">Sybat Core</a></li>
                        <li><a asp-area="" asp-controller="New" asp-action="Lavender">Lavender</a></li>
                        <li><a asp-area="" asp-controller="New" asp-action="QubitnaryNumbers">Qubitnary Numbers</a></li>
                        <li><a asp-area="" asp-controller="New" asp-action="QoKa">QoKa</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <ul>
                        <h5 style="color: #ffffff;">Education</h5>
                        <li><a asp-area="" asp-controller="Education" asp-action="QuantumBlockchainTechnology">Blockchain Technology</a></li>
                        <li><a asp-area="" asp-controller="Education" asp-action="QuantumNetwork">Quantum Network</a></li>
                        <li><a asp-area="" asp-controller="Education" asp-action="QPoS">QPoS</a></li>
                        <li><a asp-area="" asp-controller="Education" asp-action="QuantumChanneling">Quantum Channel</a></li>
                        <li><a asp-area="" asp-controller="Education" asp-action="QKD">QKD</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <ul>
                        <h5 style="color: #ffffff;">Buisness &amp; IT</h5>
                        <li><a asp-area="" asp-controller="New" asp-action="API">Sybatcoin APIs</a></li>
                        <li><a href="#">Blockchain Explorer</a></li>
                        <li><a asp-area="" asp-controller="New" asp-action="Core">Sybat Core</a></li>
                        <li><a asp-area="" asp-controller="Business" asp-action="Console">Sybat Console</a></li>
                        <li><a asp-area="" asp-controller="Business" asp-action="RPC">Sybatcoin RPC</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <ul>
                        <h5 style="color: #ffffff;">Resources</h5>
                        <li><a href="#">Blockchain Explorer</a></li>
                        <li><a href="./whitepaper/Sybatcoin.pdf">Whitepaper</a></li>
                        <li><a asp-area="" asp-controller="Resources" asp-action="Exchanges">Exchanges</a></li>
                        <li><a asp-area="" asp-controller="Dev" asp-action="Index">documentations</a></li>
                        <li><a asp-area="" asp-controller="Media" asp-action="Index">Media and Files</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 style="color: #ffffff;">Sybat Network</h5>
                    <div class="container">
                        <div class="row">
                            <div class="col order-last">
                                <a href="https://digg.com/sybatcoin"><img src="~/img/digg.png" alt="Digg" /></a>
                            </div>
                            <div class="col">
                                <a href="https://www.reddit.com/r/sybatcoin" target="_blank" rel="noopener noreferrer">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#fff" class="bi bi-reddit" viewBox="0 0 16 16">
                                        <path d="M6.167 8a.831.831 0 0 0-.83.83c0 .459.372.84.83.831a.831.831 0 0 0 0-1.661zm1.843 3.647c.315 0 1.403-.038 1.976-.611a.232.232 0 0 0 0-.306.213.213 0 0 0-.306 0c-.353.363-1.126.487-1.67.487-.545 0-1.308-.124-1.671-.487a.213.213 0 0 0-.306 0 .213.213 0 0 0 0 .306c.564.563 1.652.61 1.977.61zm.992-2.807c0 .458.373.83.831.83.458 0 .83-.381.83-.83a.831.831 0 0 0-1.66 0z"/>
                                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.828-1.165c-.315 0-.602.124-.812.325-.801-.573-1.9-.945-3.121-.993l.534-2.501 1.738.372a.83.83 0 1 0 .83-.869.83.83 0 0 0-.744.468l-1.938-.41a.203.203 0 0 0-.153.028.186.186 0 0 0-.086.134l-.592 2.788c-1.24.038-2.358.41-3.17.992-.21-.2-.496-.324-.81-.324a1.163 1.163 0 0 0-.478 2.224c-.02.115-.029.23-.029.353 0 1.795 2.091 3.256 4.669 3.256 2.577 0 4.668-1.451 4.668-3.256 0-.114-.01-.238-.029-.353.401-.181.688-.592.688-1.069 0-.65-.525-1.165-1.165-1.165z"/>
                                    </svg>
                                </a>
                            </div>
                            <div class="col order-first">
                                <a href="https://github.com/sybatcoin">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#fff" class="bi bi-github" viewBox="0 0 16 16">
                                        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                                    </svg>
                                </a>
                            </div>
                            <div class="col order-last">
                                <a href="https://t.ly/dJNi">
                                    <img src="~/img/medium.png" alt="Medium" />
                                </a>
                            </div>
                            <div class="col">
                                <a href="https://www.instagram.com/sybatcoin/">
                                    <img src="~/img/instagram.png" alt="Instagram" />
                                </a>
                            </div>
                            <div class="col order-first">
                                <a href="https://twitter.com/sybatcoin" target="_blank" rel="noopener noreferrer">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#fff" class="bi bi-twitter" viewBox="0 0 16 16">
                                        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            &copy; 2022 - Sybat Network - 
            <a asp-area="" asp-controller="Support" asp-action="Legal">Terms of Use</a>
            <a asp-area="" asp-controller="Privacy" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://cdn.jsdelivr.net/npm/@@microsoft/fast-components/dist/fast-components.min.js"></script>
    <script type="module" src="https://unpkg.com/@@fluentui/web-components"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>